details:
  namespace: student75-bookinfo-uat
  image: ghcr.io/pooripro/bookinfo-details
  tag: uat
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 1080
  healthCheckPath: "/health"
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  host: bookinfo.uat.opsta.net
  path: "/student75/details(/|$)(.*)"
  serviceType: ClusterIP